language: node_js
node_js:
  - 10
env:
  - CXX=g++-4.8
addons:
  apt:
    sources:
      - ubuntu-toolchain-r-test
    packages:
      - g++-4.8
install:
  - yarn global add vuepress
script:
  - yarn docs:build
cache:
  directories:
    - node_modules
notifications:
  email: false
deploy:
  provider: pages
  skip-cleanup: true
  local_dir: docs/.vuepress/dist
  github-token: $GITHUB_TOKEN  # Set in the settings page of your repository, as a secure variable
  repo: mostra-de-tccs-bcc/TCCs-2018
  keep-history: true
  target-branch: gh-pages
  on:
    branch: master